#!/bin/bash
# Run a local network of SSV nodes
#
# Example:
#
#    scripts/ssv/dev -n number-of-nodes (i.e. -n 4 runs 4 SSV nodes)
#
# Further information:
# See https://github.com/bloxapp/ssv
#

# Get args
while getopts :n: flag
do
    case "${flag}" in
        n) nodes=${OPTARG};;
    esac
done

if [ -z "$nodes" ]; then
    nodes=4
    echo "Number of nodes is not set, using default number $nodes"
fi

resource_path="scripts/ssv/resources"

# Deploy Casimir SSV contracts
# npm run task:compile --workspace @casimir/ethereum
# npm run deploy:ssv --workspace @casimir/ethereum -- --network geth

cd $resource_path/ssv
NODES="ssv-node-1 ssv-node-2 ssv-node-3 ssv-node-4"

# Start operators
echo "Running $nodes SSV operator nodes"
docker-compose up --build $NODES

wait && docker-compose rm -fsv && pkill -P $$