#!/bin/bash
# Create or update a Pinpoint template
#
# Example:
#
#    scripts/pinpoint/deploy -d ./path/to/pinpoint-template-directory
#
# Further information:
# See https://awscli.amazonaws.com/v2/documentation/api/latest/reference/pinpoint/create-email-template.html
#

# Get args
while getopts d: flag
do
    case "${flag}" in
        d) directory=${OPTARG};;
    esac
done

# Get variables from root .env
export $(xargs < .env)

# Set default profile
profile="consensus-networks-dev"

if [ ${PROFILE+x} ]; then
    echo "PROFILE is set to '$PROFILE'"
    profile=$PROFILE
else
    export PROFILE="$profile"
    echo "PROFILE is not set, using default profile $PROFILE"
fi

# Override project if PROJECT is set in .env
if [ ${PROJECT+x} ]; then
    echo "PROJECT is set to '$PROJECT'"
else
    export PROJECT="casimir"
    echo "PROJECT is not set, using default project $PROJECT"
fi

# Override stage if STAGE is set in .env
if [ ${STAGE+x} ]; then
    echo "STAGE is set to '$STAGE'"
else
    export STAGE="dev"
    echo "STAGE is not set, using default stage $STAGE"
fi

# Set PascalCase variables
Project=$(perl -ne 'print ucfirst' <<< $PROJECT)
Stage=$(perl -ne 'print ucfirst' <<< $STAGE)

# Loop over template folders
for template_path in $directory/* ; do
    if [ -d "$template_path" ]; then
    
        # Get current directory name
        template_dir=${template_path##*/}

        # Set PascalCase variables
        Template=$(perl -ne 'print ucfirst' <<< $template_dir)

        name=$(echo $Project$Template$Stage)
        echo "Handling $name template"

        raw_html=$(mjml $template_path/index.mjml --config.minify true)
        html=$(echo $raw_html | sed -e 's/"/\\\\"/g')

        text=$(echo $raw_html | html-to-text --ignore-image --noLinkBrackets | sed -e 's/"/\\\\"/g')
        text=$(while IFS= read -r line; do echo "$line\\\\r\\\\n"; done <<< "$text" | tr -d '\n')

        mkdir -p $template_path/template.out        
        cat $template_path/template.json | sed -e "s~%name%~$name~" -e 's/%name%/\&/g' -e "s~%html%~$html~" -e 's/%html%/\&/g' -e "s~%text%~$text~" -e 's/%text%/\&/g' > $template_path/template.out/template.json

        { 
            echo "Attempting to create pinpoint template..."
            aws pinpoint create-email-template --cli-input-json file://$template_path/template.out/template.json --profile $profile --region us-east-1 && \
            echo "✅ Successfully created pinpoint template"
            }  ||  {
            echo "Template already exists. Updating pinpoint template..."
            aws pinpoint update-email-template --cli-input-json file://$template_path/template.out/template.json --profile $profile --region us-east-1 && \
            echo "✅ Successfully updated pinpoint template"
        }

        rm -rf $template_path/template.out

    fi
done

echo "👾 Done!"
