#!/bin/bash
# Compile a ledger app

# Get args
while getopts :a: flag
do
    case "${flag}" in
        a) app=${OPTARG};;
    esac
done

if [ -z "$app" ]; then
    app="ethereum"
    echo "app is not set, using default app $app"
fi

resource_path=scripts/ledger/resources

# Compile app
echo "🔨 Building $app app for ledger"
cd $resource_path/app-$app
docker pull ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder
docker tag ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder ledger-app-builder
docker run --rm -v "$(pwd):/app" --user $(id -u $USER):$(id -g $USER) ledger-app-builder sh -c "make clean && make && exit"

# Copy app to speculos apps folder
echo "📲 Copying $app app to speculos apps folder"
cp bin/app.elf ../speculos/apps/$app.elf