#!/bin/bash
# Emulate ledger app
#
# Example:
#
#    scripts/ledger/emulate -a app-name -d device-name (i.e. -a ethereum -d nanos)
#
# Further information:
# See https://github.com/LedgerHQ/speculos
#

# Get args
while getopts a:d: flag
do
    case "${flag}" in
        a) app=${OPTARG};;
        d) device=${OPTARG};;
    esac
done

if [ -z "$app" ]; then
    app="ethereum"
    echo "app is not set, using default app $app"
fi

if [ -z "$device" ]; then
    device="nanos"
    echo "device is not set, using default device $device"
fi

resource_path=scripts/ledger/resources

if [ ! -f "$resource_path/speculos/apps/$app-$device" ]; then
    echo "App $app-$device not ready yet, running compile script"
    npm run compile:ledger --application=$app --device=$device
fi

# Emulate ledger app with speculos
echo "📺 Emulating $app app on ledger $device"
cd $resource_path/speculos
docker build . --platform linux/arm64 --tag speculos -f m1.Dockerfile
sudo docker run --platform linux/arm64 --rm -it -v "$(pwd)/apps:/speculos/apps" speculos --display text apps/$app-$device.elf