#!/bin/bash
# Emulate ledger app
#
# Example:
#
#    scripts/ledger/emulate -a app-name (i.e. -a ethereum)
#
# Further information:
# See https://github.com/LedgerHQ/speculos
#

# Get args
while getopts a: flag
do
    case "${flag}" in
        a) app=${OPTARG};;
    esac
done

if [ -z "$app" ]; then
    app="ethereum"
    echo "app is not set, using default app $app"
fi

resource_path=scripts/ledger/resources

if [ ! -f "$resource_path/speculos/apps/$app" ]; then
    echo "App $app not ready yet, running compile script"
    npm run compile:ledger --application=$app
fi

# Emulate ledger app with speculos
echo "📺 Emulating $app app on ledger"
cd $resource_path/speculos
docker build . --platform linux/arm64 --tag speculos -f ../custom/speculos-m1.Dockerfile
sudo docker run --platform linux/arm64 --rm -it -v "$(pwd)/apps:/speculos/apps" speculos --display text apps/$app.elf