export type UserAuthState = "default" 
    |"loading" 
    | "Address already exists on this account" 
    | "Address already exists as a primary address on another account"
    | "Address already exists as a secondary address on another account"
    | "Successfully added account to user"
    | "Successfully logged in"
    | "Selected address is not active address in wallet"
    | "Error in userAuthState"