/**
 * Use to pass constructor arguments to hardhat-verify
 * npm run verify --workspace @casimir/ethereum -- --constructor-args arguments.js --network goerli CONTRACT_ADDRESS
 */

const { ETHEREUM_CONTRACTS } = require("@casimir/env");

// const { ETHEREUM_CONTRACTS } = require("@casimir/env");

module.exports = [
    // Manager
    // ETHEREUM_CONTRACTS['TESTNET'].FUNCTIONS_BILLING_REGISTRY_ADDRESS,
    // ETHEREUM_CONTRACTS['TESTNET'].KEEPER_REGISTRAR_ADDRESS,
    // ETHEREUM_CONTRACTS['TESTNET'].KEEPER_REGISTRY_ADDRESS,
    // ETHEREUM_CONTRACTS['TESTNET'].LINK_TOKEN_ADDRESS,
    // ETHEREUM_CONTRACTS['TESTNET'].SSV_NETWORK_ADDRESS,
    // ETHEREUM_CONTRACTS['TESTNET'].SSV_TOKEN_ADDRESS,
    // ETHEREUM_CONTRACTS['TESTNET'].SWAP_FACTORY_ADDRESS,
    // ETHEREUM_CONTRACTS['TESTNET'].SWAP_ROUTER_ADDRESS,
    // ETHEREUM_CONTRACTS['TESTNET'].WETH_TOKEN_ADDRESS,

    // Functions Billing Registry
    // ETHEREUM_CONTRACTS['TESTNET'].LINK_TOKEN_ADDRESS,
    // ETHEREUM_CONTRACTS['TESTNET'].LINK_ETH_FEED_ADDRESS,
    // ETHEREUM_CONTRACTS['TESTNET'].FUNCTIONS_ORACLE_ADDRESS

    // factoryAddress,
    // functionsOracleAddress,
    // compoundStake
    ETHEREUM_CONTRACTS['TESTNET'].FACTORY_ADDRESS,
    ETHEREUM_CONTRACTS['TESTNET'].FUNCTIONS_ORACLE_ADDRESS,
    true
]