#!/bin/bash
# Run a local Ethereum node with Hardhat
#
# Example:
#
#    scripts/ethereum/dev -f <fork-name>
#
# Further information:
# See https://hardhat.org/hardhat-network/docs/overview
#

# Get variables from root .env
export $(xargs < .env)

# Set default profile
profile="consensus-networks-dev"

if [ ${PROFILE+x} ]; then
    echo "PROFILE is set to '$PROFILE'"
    profile=$PROFILE
else
    export PROFILE="$profile"
    echo "PROFILE is not set, using default profile '$PROFILE'"
fi

# Get args
while getopts :f: flag
do
    case "${flag}" in
        f) fork=${OPTARG};;
    esac
done

# Default to mainnet if fork is set vaguely
if [ "$fork" = true ]; then
    fork=mainnet
fi

# Get the bip39 seed from AWS
seed_secret_id=consensus-networks-bip39-seed
seed=$(aws secretsmanager get-secret-value \
--secret-id $seed_secret_id \
--query SecretString \
--output text \
--profile $profile)

# Set the shared bip39 seed
export BIP39_SEED="$seed"
echo "Your mnemonic is $BIP39_SEED"

if [ -n "$fork" ]; then
    # Get the RPC API key from AWS
    rpc_secret_id=consensus-networks-ethereum-$fork
    rpc_key=$(aws secretsmanager get-secret-value \
    --secret-id $rpc_secret_id \
    --query SecretString \
    --output text \
    --profile $profile)

    echo "⛓ Setting up ethereum chain with $fork fork"
    export ETHEREUM_FORK_RPC="https://eth-$fork.g.alchemy.com/v2/$rpc_key"
else
    echo "⛓ Setting up ethereum chain without fork"
fi

npm run dev:node --workspace @casimir/ethereum &
npm run deploy:ssv --workspace @casimir/ethereum -- --network localhost

wait && pkill -P $$


