#!/bin/bash
# Run a local ethereum node with Hardhat
#
# Example:
#
#    scripts/ethereum/dev -f <fork-name> -n <network-name>
#
# Further information:
# See https://hardhat.org/hardhat-network/docs/overview
#

# Get variables from root .env
export $(xargs < .env)

# Set default profile
profile="consensus-networks-dev"

if [ ${PROFILE+x} ]; then
    echo "PROFILE is set to '$PROFILE'"
    profile=$PROFILE
else
    export PROFILE="$profile"
    echo "PROFILE is not set, using default profile '$PROFILE'"
fi

# Get args
while getopts :f:n: flag
do
    case "${flag}" in
        f) fork=${OPTARG};;
        n) network=${OPTARG};;
    esac
done

# Expose RPC URL directly if network is set to mainnet or testnet
if [ -n "$network" ]; then
    # Get the RPC API key from AWS
    rpc_secret_id=consensus-networks-ethereum-$network
    rpc_key=$(aws secretsmanager get-secret-value \
    --secret-id $rpc_secret_id \
    --query SecretString \
    --output text \
    --profile $profile)

    export PUBLIC_ETHEREUM_RPC="https://eth-$network.g.alchemy.com/v2/$rpc_key"
    # export PUBLIC_SSV_ADDRESS="" # Todo get address (deterministic from deployer + tx count)
else
    if [ -n "$fork" ]; then
        # Get the RPC API key from AWS
        rpc_secret_id=consensus-networks-ethereum-$fork
        rpc_key=$(aws secretsmanager get-secret-value \
        --secret-id $rpc_secret_id \
        --query SecretString \
        --output text \
        --profile $profile)

        echo "⛓ Setting up ethereum chain with $fork fork"
        npm run dev:node --workspace @casimir/evm -- --fork "https://eth-$fork.g.alchemy.com/v2/$rpc_key"
    else
        echo "⛓ Setting up ethereum chain without fork"
        npm run dev:node --workspace @casimir/evm
    fi

    # npm run deploy:ssv --workspace @casimir/evm
    # export PUBLIC_SSV_ADDRESS="" # Todo get address (deterministic from deployer + tx count)
fi


