#!/bin/bash
# Test the GitHub Actions workflows in `.github/workflows`
#
# Example:
#
#    scripts/actions/test -w workflow-to-test
#
# Further information:
# See https://github.com/nektos/act
#

# Set default profile
profile="consensus-networks-dev"

if [ ${PROFILE+x} ]; then
    echo "PROFILE is set to '$PROFILE'"
    profile=$PROFILE
else
    export PROFILE="$profile"
    echo "PROFILE is not set, using default profile $PROFILE"
fi

# Get args
while getopts w: flag
do
    case "${flag}" in
        w) workflow=${OPTARG};;
    esac
done

echo "👾 Creating environment for '$profile'"

# From .env
SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL

# From AWS CLI
aws_access_key_id=$(aws configure get aws_access_key_id --profile $profile)
aws_secret_access_key=$(aws configure get aws_secret_access_key --profile $profile)

# Run selected workflow
echo "🚀 Running $workflow workflow"
act $workflow \
--rebuild \
--secret AWS_ACCESS_KEY_ID=$aws_access_key_id \
--secret AWS_SECRET_ACCESS_KEY=$aws_secret_access_key \
--verbose