#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

prompt_npm_install() {
    echo "📦 package-lock.json changed. Do you want to run 'npm install'? (y/n)"
    read answer < /dev/tty

    case "$answer" in
        [Yy]|[Yy][Ee][Ss]|"") npm install ;;
        [Nn]|[Nn][Oo]) exit ;;
        *) echo "Invalid input, please enter y or n." ;;
    esac
}

git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD --exit-code -- package-lock.json > /dev/null 2>&1 || prompt_npm_install